"""create user, integrations. personality, knowledge tables

Revision ID: 5f17c3c709c6
Revises:
Create Date: 2026-04-29 18:58:19.159446

"""

from typing import Sequence, Union

import sqlalchemy as sa
import pgvector.sqlalchemy
from alembic import op

import database.types


# revision identifiers, used by Alembic.
revision: str = "5f17c3c709c6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PAID",
                "UNPAID",
                "DEACTIVATED",
                name="userstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "knowledge_space",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "integrity",
            sa.Enum("TELEGRAM", "SLACK", name="integrity", native_enum=False),
            nullable=False,
        ),
        sa.Column("extra_info", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "integrity", name="ux_user_id_integrity"
        ),
    )
    op.create_index(
        op.f("ix_knowledge_space_user_id"),
        "knowledge_space",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "personality_dna",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("style_markers", sa.JSON(), nullable=False),
        sa.Column("core_facts", sa.JSON(), nullable=True),
        sa.Column("preferences", sa.JSON(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "version", name="ux_user_id_version"),
    )
    op.create_index(
        op.f("ix_personality_dna_user_id"),
        "personality_dna",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_integrity",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "integrity",
            sa.Enum("TELEGRAM", "SLACK", name="integrity", native_enum=False),
            nullable=False,
        ),
        sa.Column("integrity_user_id", sa.String(length=64), nullable=True),
        sa.Column(
            "credentials", database.types.EncryptedJSON(), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACTIVE",
                "INACTIVE",
                "EXPIRED",
                "REVOKED",
                name="integritystatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "integrity_user_id", "integrity", name="uq_integrity_uid_integrity"
        ),
    )
    op.create_index(
        op.f("ix_user_integrity_integrity_user_id"),
        "user_integrity",
        ["integrity_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_integrity_user_id"),
        "user_integrity",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "knowledge",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_space_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1536),
            nullable=False,
        ),
        sa.Column("embedding_model", sa.String(length=30), nullable=False),
        sa.Column(
            "scope",
            sa.Enum(
                "GLOBAL", "PRIVATE", name="knowledgescope", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "source_type",
            sa.Enum(
                "PRIVATE_CHAT",
                "GROUP_CHAT",
                name="knowledgesourcetype",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("source_id", sa.String(length=64), nullable=True),
        sa.Column("interceptor_id", sa.String(length=64), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("extra_info", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_space_id"],
            ["knowledge_space.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "knowledge_space_id",
            "source_id",
            "interceptor_id",
            "version",
            name="ux_space_source_interceptor_version",
        ),
    )
    op.create_index(
        op.f("ix_knowledge_interceptor_id"),
        "knowledge",
        ["interceptor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_knowledge_space_id"),
        "knowledge",
        ["knowledge_space_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_source_id"),
        "knowledge",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        "ix_source_id_interceptor_id",
        "knowledge",
        ["source_id", "interceptor_id"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_embedding",
        "knowledge",
        ["embedding"],
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_source_id_interceptor_id", table_name="knowledge")
    op.drop_index(op.f("ix_knowledge_source_id"), table_name="knowledge")
    op.drop_index(
        op.f("ix_knowledge_knowledge_space_id"), table_name="knowledge"
    )
    op.drop_index(op.f("ix_knowledge_interceptor_id"), table_name="knowledge")
    op.drop_table("knowledge")
    op.drop_index(
        op.f("ix_user_integrity_user_id"), table_name="user_integrity"
    )
    op.drop_index(
        op.f("ix_user_integrity_integrity_user_id"),
        table_name="user_integrity",
    )
    op.drop_table("user_integrity")
    op.drop_index(
        op.f("ix_personality_dna_user_id"), table_name="personality_dna"
    )
    op.drop_table("personality_dna")
    op.drop_index(
        op.f("ix_knowledge_space_user_id"), table_name="knowledge_space"
    )
    op.drop_table("knowledge_space")
    op.drop_table("user")
    # ### end Alembic commands ###
