"""encryping fields with user's privacy data

Revision ID: c1f51803b156
Revises: 5f17c3c709c6
Create Date: 2026-04-30 16:50:36.737305

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import database.types

# revision identifiers, used by Alembic.
revision: str = "c1f51803b156"
down_revision: Union[str, Sequence[str], None] = "5f17c3c709c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "knowledge",
        "extra_info",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=database.types.EncryptedJSON(),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_knowledge_embedding"),
        table_name="knowledge",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.alter_column(
        "personality_dna",
        "style_markers",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=database.types.EncryptedJSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "personality_dna",
        "core_facts",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=database.types.EncryptedJSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "personality_dna",
        "preferences",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=database.types.EncryptedJSON(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "personality_dna",
        "preferences",
        existing_type=database.types.EncryptedJSON(),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "personality_dna",
        "core_facts",
        existing_type=database.types.EncryptedJSON(),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "personality_dna",
        "style_markers",
        existing_type=database.types.EncryptedJSON(),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_knowledge_embedding"),
        "knowledge",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.alter_column(
        "knowledge",
        "extra_info",
        existing_type=database.types.EncryptedJSON(),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
