"""user_id_integration Unique Constaint in UserIntegration

Revision ID: c3bd5a865e32
Revises: ad04a97fc516
Create Date: 2026-05-22 18:37:18.995050

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c3bd5a865e32"
down_revision: Union[str, Sequence[str], None] = "ad04a97fc516"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_id_integration",
        "user_integration",
        ["user_id", "integration"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_user_id_integration", "user_integration", type_="unique"
    )
    # ### end Alembic commands ###
