name: Test code

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      
      - name: Install uv
        uses:  astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Create .env
        run: echo "${{ secrets.TEST_ENV_FILE_CONTENT }}" > .env

      - name: Run tests and check coverage
        run: uv run coverage run --source=perceiver_service/src -m pytest && uv run coverage report --fail-under=80
